"""Add price to Booking

Revision ID: eacd3cebd7ce
Revises: ef9dcfd7516f
Create Date: 2025-05-03 05:27:54.168358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eacd3cebd7ce'
down_revision = 'ef9dcfd7516f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
